// Script để khởi tạo danh sách sản phẩm JOICO mặc định vào localStorage

const initializeJOICOProducts = () => {
  const defaultProducts = [
    // Hair Care Products
    {
      id: 'youthlock-shampoo',
      name: 'YouthLock™',
      category: 'Hair Care',
      line: 'YouthLock',
      price: 360000,
      volume: '300ml',
      description: 'Tóc lão hóa',
      benefits: ['Chống lão hóa', 'Phục hồi độ đàn hồi', 'Tăng cường sức khỏe tóc'],
      hairTypes: ['aging', 'mature'],
      rating: 4.8,
      reviews: 1200,
      image: '',
      inStock: true,
      bestseller: false,
      newProduct: false,
      trending: false,
      customerChoice: false,
      essential: false,
      specialized: false,
      professional: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'defy-damage-shampoo',
      name: 'Defy Damage®',
      category: 'Hair Care',
      line: 'Defy Damage',
      price: 330000,
      volume: '300ml',
      description: 'Tóc dễ hư tổn',
      benefits: ['Bảo vệ khỏi hư tổn', 'Tăng cường sức mạnh', 'Phục hồi cấu trúc'],
      hairTypes: ['damaged', 'chemically_treated'],
      rating: 4.9,
      reviews: 2100,
      image: '',
      inStock: true,
      bestseller: true,
      newProduct: false,
      trending: false,
      customerChoice: false,
      essential: true,
      specialized: false,
      professional: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'kpak-shampoo',
      name: 'K-PAK®',
      category: 'Hair Care',
      line: 'K-PAK',
      price: 350000,
      volume: '300ml',
      description: 'Tóc hư tổn',
      benefits: ['Phục hồi tóc hư tổn', 'Tăng cường độ bền', 'Làm mềm tóc'],
      hairTypes: ['damaged', 'chemically_treated', 'weak'],
      rating: 4.8,
      reviews: 1250,
      image: '',
      inStock: true,
      bestseller: true,
      newProduct: false,
      trending: false,
      customerChoice: false,
      essential: true,
      specialized: false,
      professional: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'kpak-color-therapy',
      name: 'K-PAK® Color Therapy',
      category: 'Color Care',
      line: 'K-PAK',
      price: 350000,
      volume: '300ml',
      description: 'Tóc đã nhuộm',
      benefits: ['Bảo vệ màu nhuộm', 'Phục hồi tóc hư tổn', 'Giữ màu lâu'],
      hairTypes: ['chemically_treated', 'colored'],
      rating: 4.7,
      reviews: 980,
      image: '',
      inStock: true,
      bestseller: false,
      newProduct: false,
      trending: false,
      customerChoice: false,
      essential: false,
      specialized: true,
      professional: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'joifull-shampoo',
      name: 'JoiFull',
      category: 'Hair Care',
      line: 'JoiFull',
      price: 350000,
      volume: '300ml',
      description: 'Tóc mỏng / trung bình',
      benefits: ['Tăng độ dày', 'Tạo volume', 'Làm đầy tóc'],
      hairTypes: ['fine', 'medium', 'thin'],
      rating: 4.6,
      reviews: 750,
      image: '',
      inStock: true,
      bestseller: false,
      newProduct: false,
      trending: false,
      customerChoice: false,
      essential: false,
      specialized: true,
      professional: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'hydrasplash-shampoo',
      name: 'HydraSplash®',
      category: 'Hair Care',
      line: 'HydraSplash',
      price: 350000,
      volume: '300ml',
      description: 'Tóc khô, mỏng / trung bình',
      benefits: ['Cấp ẩm sâu', 'Làm mềm tóc', 'Giảm khô xơ'],
      hairTypes: ['dry', 'fine', 'medium'],
      rating: 4.5,
      reviews: 650,
      image: '',
      inStock: true,
      bestseller: false,
      newProduct: false,
      trending: false,
      customerChoice: false,
      essential: false,
      specialized: true,
      professional: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'moisture-recovery-shampoo',
      name: 'Moisture Recovery',
      category: 'Hair Care',
      line: 'Moisture Recovery',
      price: 350000,
      volume: '300ml',
      description: 'Tóc khô, dày / sợi to',
      benefits: ['Phục hồi độ ẩm', 'Làm mềm tóc dày', 'Giảm khô xơ'],
      hairTypes: ['dry', 'thick', 'coarse'],
      rating: 4.4,
      reviews: 580,
      image: '',
      inStock: true,
      bestseller: false,
      newProduct: false,
      trending: false,
      customerChoice: false,
      essential: false,
      specialized: true,
      professional: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    // Color Care Products
    {
      id: 'blonde-life-shampoo',
      name: 'Blonde Life®',
      category: 'Color Care',
      line: 'Blonde Life',
      price: 350000,
      volume: '300ml',
      description: 'Tóc vàng blonde',
      benefits: ['Bảo vệ màu vàng', 'Ngăn vàng đồng', 'Giữ màu sáng'],
      hairTypes: ['blonde', 'light'],
      rating: 4.6,
      reviews: 890,
      image: '',
      inStock: true,
      bestseller: false,
      newProduct: false,
      trending: false,
      customerChoice: false,
      essential: false,
      specialized: true,
      professional: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'blonde-life-violet-shampoo',
      name: 'Blonde Life® Violet',
      category: 'Color Care',
      line: 'Blonde Life',
      price: 350000,
      volume: '300ml',
      description: 'Tóc vàng blonde lạnh',
      benefits: ['Trung hòa vàng đồng', 'Giữ màu lạnh', 'Tăng độ sáng'],
      hairTypes: ['blonde', 'cool_blonde'],
      rating: 4.7,
      reviews: 720,
      image: '',
      inStock: true,
      bestseller: false,
      newProduct: false,
      trending: false,
      customerChoice: false,
      essential: false,
      specialized: true,
      professional: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'colorful-shampoo',
      name: 'Colorful',
      category: 'Color Care',
      line: 'Colorful',
      price: 350000,
      volume: '300ml',
      description: 'Tóc đã nhuộm',
      benefits: ['Bảo vệ màu nhuộm', 'Giữ màu lâu', 'Làm mềm tóc'],
      hairTypes: ['colored', 'chemically_treated'],
      rating: 4.5,
      reviews: 680,
      image: '',
      inStock: true,
      bestseller: false,
      newProduct: false,
      trending: false,
      customerChoice: false,
      essential: false,
      specialized: true,
      professional: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'color-infuse-red-shampoo',
      name: 'Color Infuse® Red',
      category: 'Color Care',
      line: 'Color Infuse',
      price: 350000,
      volume: '300ml',
      description: 'Tóc nhuộm đỏ',
      benefits: ['Bảo vệ màu đỏ', 'Giữ màu sáng', 'Ngăn phai màu'],
      hairTypes: ['red', 'colored'],
      rating: 4.4,
      reviews: 520,
      image: '',
      inStock: true,
      bestseller: false,
      newProduct: false,
      trending: false,
      customerChoice: false,
      essential: false,
      specialized: true,
      professional: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'color-balance-blue-shampoo',
      name: 'Color Balance® Blue',
      category: 'Color Care',
      line: 'Color Balance',
      price: 350000,
      volume: '300ml',
      description: 'Tóc nhuộm nâu lạnh hoặc xám xanh rêu',
      benefits: ['Trung hòa vàng', 'Giữ màu lạnh', 'Tăng độ sáng'],
      hairTypes: ['cool_brown', 'ash_green'],
      rating: 4.3,
      reviews: 450,
      image: '',
      inStock: true,
      bestseller: false,
      newProduct: false,
      trending: false,
      customerChoice: false,
      essential: false,
      specialized: true,
      professional: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'color-balance-purple-shampoo',
      name: 'Color Balance® Purple',
      category: 'Color Care',
      line: 'Color Balance',
      price: 350000,
      volume: '300ml',
      description: 'Tóc vàng ánh xám hoặc xám',
      benefits: ['Trung hòa vàng', 'Giữ màu xám', 'Tăng độ sáng'],
      hairTypes: ['ash_blonde', 'grey'],
      rating: 4.5,
      reviews: 610,
      image: '',
      inStock: true,
      bestseller: false,
      newProduct: false,
      trending: false,
      customerChoice: false,
      essential: false,
      specialized: true,
      professional: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    }
  ];

  // Lưu vào localStorage
  localStorage.setItem('managedProducts', JSON.stringify(defaultProducts));
  console.log('✅ Đã khởi tạo', defaultProducts.length, 'sản phẩm JOICO vào localStorage');
  
  return defaultProducts;
};

// Export function để sử dụng trong các component khác
export default initializeJOICOProducts;

// Tự động chạy khi import
if (typeof window !== 'undefined') {
  // Chỉ chạy nếu localStorage chưa có managedProducts
  if (!localStorage.getItem('managedProducts')) {
    initializeJOICOProducts();
  }
}
